### ISSUE TITLE
Why is the `README` a `.adoc` file instead of a `.md`?

### ISSUE THREAD

**Issue by nilsreichardt** [MaximilianAnzinger/pgdp2223-tests#12]
Just out of interest: Why is the `README` not a typical `.md` file because this normally the standard for `README` files on GitHub 🤔

**Comment by MaximilianAnzinger** [comment]
This post covers some differences between AsciiDoc and Markdown: https://github.com/asciidoctor/asciidoctor.org/issues/34
I enjoy showing students new stuff and sometimes students stumble upon minor details like this. With little luck, they get curious and learn something new (I suppose you are one of them.)

**Comment by MaximilianAnzinger** [comment]
This is a [discussion](https://github.com/MaximilianAnzinger/pgdp2223-tests/discussions)  not an actual issue
