### ISSUE TITLE
[W06H02] popShouldReturnCorrectValues tests irrelevant Stack contents

### ISSUE THREAD

**Issue by Vyquos** [MaximilianAnzinger/pgdp2223-tests#125]
`popShouldReturnCorrectValues()` prüft den Stack auf Gleichheit mit dem Array `int[]{0}`, nachdem das letzte verbleibende Wert aus dem Stack ge`pop()`ed wurde:
https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/f925297e3696b4a5226aad552e08ad429638044d/w06h02/test/pgdp/ds/MultiStackTest.java#L231
Laut Tutoren ist der Inhalt der ge`pop()`ed Zellen aber egal:
[https://zulip.in.tum.de/PGdP-W06H02/pop](https://zulip.in.tum.de/#narrow/stream/1480-PGdP-W06H02/topic/pop.28.29.20muss.20mem.20ver.C3.A4ndert.20werden.3F)
Stattdessen müsste geprüft werden, ob der `top`-Pointer gleich `-1` ist (und evtl, dass nach dem Ersten Stack keine weiteren mehr sind):
```java
int getTopPointer(Stack s) {
    try {
        final var field = s.getClass().getDeclaredField("top");
        field.setAccessible(true);
        return (int) field.get(s);
    catch (IllegalAccessException | NoSuchFieldException e) {
        throw new RuntimeException(e);
    }
}
```
und in `popShouldReturnCorrectValues()`:
```java
assertEquals(-1, getTopPointer(getHead()));
```

**Comment by HendrikHuebner** [comment]
Ok, das war halt mal wieder blöd formuliert auf Artemis.

**Comment by Vyquos** [comment]
yup

**Comment by HendrikHuebner** [comment]
willst du es dann einfach selber schnell ändern oder soll ich das machen?

**Comment by Vyquos** [comment]
Kann ich machen :+1:
