### ISSUE TITLE
W07H02 TrackTest printStatus()

### ISSUE THREAD

**Issue by LeoWoehler** [MaximilianAnzinger/pgdp2223-tests#137]
Artemis erwartet hir am ende noch ein zeilenumbruch.

**Comment by julian-hartl** [comment]
Ist in Arbeit 👍

**Comment by julian-hartl** [comment]
@LeoWoehler PR #138 ist offen. Kannst mal kurz drüber gucken, ob das jetzt so passt.

**Comment by felixhauptmann** [comment]
Can we close this?
