### ISSUE TITLE
[W07H02] Fix linebreaks

### ISSUE THREAD

**Issue by Friendly-Banana** [MaximilianAnzinger/pgdp2223-tests#145]
@julian-hartl Mehrere Leute hatten jetzt Probleme mit den Line endings, weil Windows \r\n statt normalem \n nutzt.
Tools wie IntelliJ ersetzen das, auch auf Windows, dann failt aber System.lineSeparator(). Deswegen Vorschlag:
Im output alle \r\n durch \n ersetzen und expected mit \n schreiben.

**Comment by julian-hartl** [comment]
@Friendly-Banana Sollte funktionieren.

**Comment by julian-hartl** [comment]
@Friendly-Banana Werde da heute nicht mehr zu kommen. Wenn du willst, kannst du das gerne ändern.

**Comment by felixhauptmann** [comment]
Auf welche Tests bezieht sich das konkret?

**Comment by julian-hartl** [comment]
> Auf welche Tests bezieht sich das konkret?

@felixhauptmann printStatus im TrackTest (Woche 7 Aufgabe 2)

**Comment by felixhauptmann** [comment]
afaik nutzt MacOS aber \r von daher müsste man den Fall auch abdecken... da stellt sich dann die frage ob man nicht einfach erwarten kann dass die Leute die Methode entsprechend "richtig" implementieren.

**Comment by Friendly-Banana** [comment]
Ist jetzt die Frage ob der Test "manuell" unterstützen soll. 
Wir können erst \r\n durch \n und dann \r duch \n ersetzen, dann sollte auch MacOS gehen.

Natürlich können wir auch einfach println empfehlen, dann sollte System.lineSeparator gehen.
