### ISSUE TITLE
w09b01 AITests falsch

### ISSUE THREAD

**Issue by HendrikHuebner** [MaximilianAnzinger/pgdp2223-tests#211]
Bei AITests erwarten tests 37 bis 66 alle, dass der gegnerische Gewinnzug mit den werten 7 oder 8 blockiert werden. Das muss allerdings nicht der Fall sein um den Sieg zu blockieren.

Die Tests 60, 56, 54 sind komplett falsch, da es bei ihnen keine Möglichkeit gibt den sieg des Gegners zu verhindern. Also ist der nächste zug undefiniert. Evtl. gibt es noch mehr problematische tests. Bitte noch einmal drüber gucken.

**Comment by DominikGleissner** [comment]
Naja also man muss schon mit einem hohen Stein blocken. Wenn ich einen zu niedrigen nehme, kann der Gegner danach meinen Stein überdecken und damit auch direkt in diesem Zug gewinnen. Ich brauche also einen so hohen, dass der Gegner keinen mehr darauflegen kann. Aber kann gut sein, dass da einzelne Tests etwas zu streng sind, wobei ich da direkt auch keine finde... also ich bin einige überflogen und die haben desbezüglich schon gepasst meines Erachtens nach.

**Comment by HendrikHuebner** [comment]
> kann der Gegner danach meinen Stein überdecken und damit auch direkt in diesem Zug gewinnen
Nein, das ist falsch. Wenn du den gegnerischen stein zum blockieren überschreibst braucht er ja zwei züge um zu gewinnen. 

Ich überarbeite die tests jetzt

**Comment by MaximilianAnzinger** [comment]
Da die Deadline der 8. Januar war, werde ich dieses Issue schließen.
