### ISSUE TITLE
[W09H03] Private Access for tests 

### ISSUE THREAD

**Issue by mbmueller** [MaximilianAnzinger/pgdp2223-tests#224]
The tests cant access the private attribute 'frameStream' in class VideoContainer.java

**Comment by nilsreichardt** [comment]
At the top is a note what attributes and classes need be `public`: 

https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/5e2a53a2a3166185c04655168b28cde75a4d94cb/w09h03/test/pgdp/filter/DGTest.java#L29

**Comment by mbmueller** [comment]
Why dont just use the getter Method here?

**Comment by nilsreichardt** [comment]
Because this is a temporary fix to get the tests running. Ideally, you should also revert the changes before submitting to Artemis.

**Comment by felixhauptmann** [comment]
Resolved by #220
