### ISSUE TITLE
[W09B01] Remove Test 53

### ISSUE THREAD

**Issue by mrcfschr** [MaximilianAnzinger/pgdp2223-tests#227]
```
@Test
    @DisplayName("DG Test 53 mehrere gewinne verhindern erster spieler spalte und zeile test 1")
    public void test53() {
        this.board = new Field[][]{
                {null, new Field(0, false), new Field(1, false)},
                {new Field(2, false), null, null},
                {new Field(3, false), null, null}};
        this.firstPlayedMoves = new boolean[]{
                false, false, false,
                false, false, false,
                false, false, false};
        this.secondPlayedMoves = new boolean[]{
                true, true, true,
                true, false, false,
                false, false, false};

        Move move = this.ai.makeMove(this.board, true, this.firstPlayedMoves, this.secondPlayedMoves);

        Assertions.assertEquals(0, move.x());
        Assertions.assertEquals(0, move.y());
        Assertions.assertEquals(8, move.value());

    }
```
Please correct me if I'm wrong, but this test doesn't make sense to me, and I think it should be removed. It's expected to place a piece in the upper left corner 0,0 but the opponent would still win if they place a piece in the center of the board at 1,1. There is no move to win in this scenario, so I don't think it makes sense to test for a specific move.
The same is true for test 57 
https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/main/w09b01/pgdp/AITests.java#L1383-L1404
and 61
https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/main/w09b01/pgdp/AITests.java#L1455-L1476

**Comment by ZhuoshZhuosh** [comment]
Yep just posted about this in https://github.com/MaximilianAnzinger/pgdp2223-tests/issues/209#issuecomment-1372679318

Other tests has this problem too

**Comment by mrcfschr** [comment]
oh sorry about the duplicate
