### ISSUE TITLE
w03h03 bad gradientMagnitude given in testing_build_seams_seamsArray

### ISSUE THREAD

**Issue by Garfield100** [MaximilianAnzinger/pgdp2223-tests#27]
@felixhauptmann you are the first person I can tag, I can't tag yannic

In SeamCarvingTest.java, starting on line 163, the following is given as gradientMagnitude for the test.

```
new int[]{
        Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE,
        1, 1, 1, 1, 1, 1,
        69, 420, 42, 42, 42, 1337,
        100, 10, 666, 20, 3, 10,
        Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE
 }
```

why does this not have Integer.MAX_VALUE on the right and left sides as well?
This causes both testing_build_seams_seamWeights tests to fail for me.
I believe it should look like this:
```
new int[]{
        Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE,
        Integer.MAX_VALUE, 1, 1, 1, 1, Integer.MAX_VALUE,
        Integer.MAX_VALUE, 420, 42, 42, 42, Integer.MAX_VALUE,
        Integer.MAX_VALUE, 10, 666, 20, 3, Integer.MAX_VALUE,
        Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE
 }
```

Have I misunderstood something or shall I adjust the test?

**Comment by felixhauptmann** [comment]
You're right. In practice there should be `Integer.MAX_VALUE` at all outer edges.

But unless the expected values are wrong or your implementation depends on the outer edges this shouldn't fail.

We could keep this test for strict testing (and annotate it accordingly) and therefore add another test with `Integer.MAX_VALUE` edges so implementations like yours can be tested as well.

Do you pass all the other tests?

**Comment by Garfield100** [comment]
Yes, I passed all the other tests except for the two that did this. As a byproduct of trying to deal with widths below 3, my code now passes these tests too. In a way, the test still helped me :)

**Comment by felixhauptmann** [comment]
Can we close this issue?

**Comment by Garfield100** [comment]
sure
