### ISSUE TITLE
login - unsuccessful test incorrect

### ISSUE THREAD

**Issue by felixhauptmann** [MaximilianAnzinger/pgdp2223-tests#279]
The test expects username and password fields to be null after failure to login despite the specification stating that these fields are supposed to get set as soon as the token request succeeds.

**Comment by BjarneHa** [comment]
I thought we had asked in the Zulip about this? Weren't you the person who originally told me to change that?

**Comment by felixhauptmann** [comment]
No, i cant remember anything about that. Can you link the zulip post.

**Comment by BjarneHa** [comment]
Nevermind it was @nilsreichardt.

[Git-Hub thread](https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/274#discussion_r1082847778)
[Zulip-Link](https://zulip.in.tum.de/#narrow/stream/1525-PGdP-W11H03/topic/login.20Methode.20Attribute/near/909604)

**Comment by felixhauptmann** [comment]
Good point. I will convert the PR to draft

**Comment by felixhauptmann** [comment]
https://zulip.in.tum.de/#narrow/stream/1525-PGdP-W11H03/topic/login.20Methode.20Attribute/near/910480

How should we proceed? just remove the two assertions?

**Comment by BjarneHa** [comment]
I'll just test for both cases. There'll be a PR with tons of fixes in a bit.

**Comment by nilsreichardt** [comment]
> How should we proceed? just remove the two assertions?

I think removing the assertions would not the best idea because it woudl be against the task to set the attributes when the login was unsuccessful (https://zulip.in.tum.de/#narrow/stream/1525-PGdP-W11H03/topic/login.20Methode.20Attribute/near/909609)

**Comment by felixhauptmann** [comment]
> > How should we proceed? just remove the two assertions?
> 
> I think removing the assertions would not the best idea because it woudl be against the task to set the attributes when the login was unsuccessful (https://zulip.in.tum.de/#narrow/stream/1525-PGdP-W11H03/topic/login.20Methode.20Attribute/near/909609)

https://zulip.in.tum.de/#narrow/stream/1525-PGdP-W11H03/topic/login.20Methode.20Attribute/near/910480

This would mean that it is irrelevant if the two attributes are set if the login is unsuccessful as long as there is a token.

**Comment by felixhauptmann** [comment]
> I'll just test for both cases. There'll be a PR with tons of fixes in a bit.

Testing for both cases is equivalent to what i proposed in #281

**Comment by BjarneHa** [comment]
I feel like it's fine for us to continue to test for null attributes, even though it might not technically be required. It doesn't make the implementation any more difficult and I feel like there are good reasons not to do it (past statements made by Konrad). It definitely doesn't hurt to only set attributes if login succeeds.

**Comment by BjarneHa** [comment]
But who knows, maybe I'm being to careful here. I've been traumatized by incorrect statements from the ÜL.

**Comment by felixhauptmann** [comment]
Yeah I agree that it doesn't hurt (and I definitely am with you regarding the traumatization xD) even tough Konrad clearly stated that [it does not matter](https://zulip.in.tum.de/#narrow/stream/1525-PGdP-W11H03/topic/login.20Methode.20Attribute/near/910480) in this case.
