### ISSUE TITLE
[W11B01] Falsch Negativer Test für findPath

### ISSUE THREAD

**Issue by mbmueller** [MaximilianAnzinger/pgdp2223-tests#286]
Der Test findPath schlägt bei mir mit dem 5. Parameter fehl. Es kommt folgende Ausgabe:

```
digraph {
b -> t [label="0/1"];
b -> c [label="0/1"];
s -> a [label="0/1"];
a -> b [label="0/1"];
a -> t [label="0/1"];
c -> t [label="0/1"];
c -> a [label="0/1"];
}
Your path was: s -> a -> b -> t
```

Auf Artemis passen die Tests jedoch.

**Comment by simihod** [comment]
Der Test findPath passed für den zweiten Parameter. Folgede Ausgabe erscheint auf der Konsole:
`digraph {
s -> a [label="0/1"];
b -> t [label="0/1"];
b -> c [label="0/1"];
a -> b [label="0/1"];
a -> c [label="0/1"];
c -> t [label="0/1"];
}
Your path was: s -> a -> b`

Der Test sollte eigentlich nicht passen, da kein Path zu t gefunden wurde.

**Comment by felixhauptmann** [comment]
> digraph {
> s -> a [label="0/1"];
> b -> t [label="0/1"];
> b -> c [label="0/1"];
> a -> b [label="0/1"];
> a -> c [label="0/1"];
> c -> t [label="0/1"];
> }
> Your path was: s -> a -> b

Kannst du dafür bitte einen eigenen issue aufmachen, da das nichts miteinader zu tun hat und ein bisschen genauer erläutern, wann bei dir der Fehler auftritt.
