### ISSUE TITLE
[W12H03] ShuttleProcessorTests shutDownTest() should not add task silently

### ISSUE THREAD

**Issue by meandaD** [MaximilianAnzinger/pgdp2223-tests#295]
Hi,
in this test, after a thread ShuttleProcessor is started, a task is added into its task queue with help of Reflection. This action is completely silent.

```java
@Test
@DisplayName("Should wait until current task has finished evaluating when shut down")
public void shutDownTest() throws InterruptedException, NoSuchFieldException, IllegalAccessException {
    var taskchecker = new TaskChecker(null, null);
    var sp = new ShuttleProcessor(taskchecker);
    var taskGen = new TestTaskGenerator(0, 5, 0);

    sp.start();
    getTaskQueue(sp).add(taskGen.generateSlowTask()); // slow task takes 50ms to evaluate

    Thread.sleep(10);
    sp.shutDown();

    Thread.sleep(10);

    assertEquals("ShuttleProcessor shutting down.\n", out.toString());
    assertTrue(sp.isAlive(), "Should have waited for slow task to finish evaluating.");

    Thread.sleep(35); //enough time to finish evaluating slow task

    assertFalse(sp.isAlive(), "Slow task finished, the thread should have shut down by now.");
}
```

In my opinion, one of the following three changes would make sence:
1. add the task into taskQueue via Reflection **before** starting the thread, as following:
    ```java
    getTaskQueue(sp).add(taskGen.generateSlowTask()); // slow task takes 50ms to evaluate
    sp.start();
    ```
    I noticed that in test `testEvaluatePriority()` it was done this way.

2. call `notify()` after adding task into the taskQueue via Reflection, as following:
    ```java
    sp.start();
    getTaskQueue(sp).add(taskGen.generateSlowTask()); // slow task takes 50ms to evaluate
    synchronized (sp) {
        sp.notify();
    }
    ```
    In `testAddTaskWhileRunning()` and `waitNotifyTest()` it is done this way.

3. call `ShuttleProcessor.addTask()` instead of using Reflection, as following:
    ```java
    sp.start();
    sp.addTask(taskGen.generateSlowTask()); // slow task takes 50ms to evaluate
    ```
    As same as that in `interruptTest()`.

---
Please correct me if I'm misunderstanding this test. Thanks for viewing :D

**Comment by HendrikHuebner** [comment]
I actually used addTask before, but them @DominikGleissner complained that it wasn't working for his implementation because he called notify() in the addTask method directly. I then changed it to add the tasks via reflection. Its kind of difficult to make this work for all implementations.

**Comment by meandaD** [comment]
Thank you for your reply. I think for testing, the specific implementation of the method is irrelevant, and the test can simulate the use of these methods in actual scenarios. In this case for example, my 3rd version above is (I think) the normal usage of these methods.
In the case of "directly calling notify() in the addTask method", I think it's no problem? I'm not saying that in the test we should call `sp.notify()` after `sp.addTask()`.

**Comment by HendrikHuebner** [comment]
Actually you were right, there is a mistake here. I didn't understand what you were saying and first and thought you menat something else. Some other guy is fixing this right now.

**Comment by meandaD** [comment]
Thank you :D

**Comment by nilsreichardt** [comment]
Closing because the deadline is over
