### ISSUE TITLE
W03H03 shrink seam imageToArray helper function causes segfault

### ISSUE THREAD

**Issue by hmelder** [MaximilianAnzinger/pgdp2223-tests#30]
The image.getGraphics() causes a segmentation fault with Zulu JDK 17 on an M1 Macbook Pro running 12.6. The native ImageIO.framework tries to access an invalid memory location. The image is correctly loaded into the BufferedImage object. Might be a deeply-nested bug.

Here the core dump:
[hs_err_pid7400.log](https://github.com/MaximilianAnzinger/pgdp2223-tests/files/9984714/hs_err_pid7400.log)

**Comment by hmelder** [comment]
Choosing a different JDK vendor causes the same crash.

**Comment by hmelder** [comment]
Testing it on a Windows on ARM Developer Enterprise VM with a native aarch64 jbr runtime works. Must be a platform issue.

**Comment by hmelder** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/45601940/201213380-7258d5a5-c6b9-4e59-8d7d-28a52c28de2e.png">

**Comment by nilsreichardt** [comment]
cc: @felixhauptmann

**Comment by felixhauptmann** [comment]
That's bad

**Comment by nilsreichardt** [comment]
Either we fix it or we write a quick comment in the code that it's only working with Windows and you should use a VM if you want to run the test. I think the second option is enough.
