### ISSUE TITLE
w13h03

### ISSUE THREAD

**Issue by AlexanderGlas** [MaximilianAnzinger/pgdp2223-tests#306]
Hello, 
I belive that the tests of UnitTest of w13h03 expect the wrong order of inputs, e.g. for the code 

const 2
const 4
div
write
halt

They would expect 4/2=2 instead of 2/4=0 . However I may be mistaken. Thanks for writing the tests and have a good day.

**Comment by nico-lintn** [comment]
Hi, the order of operands is expected to be this way (but only in W13H03). Also refer to this [Thread on Zulip](https://zulip.in.tum.de/#narrow/stream/1533-PGdP-W13H03/topic/.E2.9C.94.20Umgekehrte.20Instruction.20Input.20Reihenfolge/near/928476).

**Comment by AlexanderGlas** [comment]
Ah, wer lesen kann ist klar im Vorteil. Thanks for the heads up!
