### ISSUE TITLE
Expected und Actual vertauscht bei W04H02

### ISSUE THREAD

**Issue by MoLaden** [MaximilianAnzinger/pgdp2223-tests#41]
Meine Tests bei der Aufgabe sind (zurecht) gefailt. Allerdings war bei der Konsolenausgabe Actual und Expected vertauscht.
Hat mich anfangs sehr verwirrt. 
![image](https://user-images.githubusercontent.com/46149561/201471857-1e481aae-988f-4cde-8b05-c0e929de2af0.png)
Der hier gefailte Test ist in Zeile 111, es gilt aber auch für andere Tests. Vermutlich wurde einfach die Reihenfolge der Parameter von AssertArrayEquals vertauscht.

**Comment by MaximilianAnzinger** [comment]
https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/42
