### ISSUE TITLE
Typo in README.adoc - 1. Legal Status

### ISSUE THREAD

**Issue by JGStyle** [MaximilianAnzinger/pgdp2223-tests#6]
Hey, I did not want to make an extra PR for this, just wanted to point out that there's a typo in the readme in this section

> Furthermore, there is no guarantee of the correctness of the tests. Neither the Übungsleitung nor any of the other tutors will contribute own tests. We (Maximilian Anzinger, Johannes Stöhr, Georg Henning, Konrad Gößmann, Robin Marchart, Oliver Specht, and Anton Kluge) will just make shure that there are no tests that reveal the solution. It is your own responsibility to validate the correctness and if necessary report bugs or even provide/contribute a fix for your fellow student.

under 1. Legal Status

In the second sentence you say 
> We (...) will just make **shure** that..

https://dictionary.cambridge.org/de/worterbuch/englisch-deutsch/make-sure

As far as I am concerned there should be no h in the word sure.

**Comment by MaximilianAnzinger** [comment]
You are right, thank you
c723df5
