### ISSUE TITLE
[W04H02] Unnötiger Test MegaMergeSort

### ISSUE THREAD

**Issue by JGStyle** [MaximilianAnzinger/pgdp2223-tests#72]
In den aktuellen Tests zu W04H02 in der Datei MergeTest.java in Zeile 120 werden Werte getestet, bei denen to größer ist als die Array länge.

Diese tests sollten zumindest als Optional markiert werden, da sie nicht von Relevanz sind wie Georg Henning auf Zulip beantwortet hat:

![image](https://user-images.githubusercontent.com/51161233/202862233-dc62140e-7075-4b62-9751-6b8dfe72b403.png)

https://zulip.in.tum.de/#narrow/stream/1450-PGdP-W04H02/topic/.E2.9C.94.20Sinnvolle.20Indizes

**Comment by ipadmini22** [comment]
Leider gibts dazu noch diese Nachricht: [Link](https://zulip.in.tum.de/#narrow/stream/1450-PGdP-W04H02/topic/to.20.3C.20from/near/803016). Bis dahin lieber die Tests einbauen... ist mal wieder ne richtige tolle Aktion :D

**Comment by JGStyle** [comment]
Na das ist ja toll, dabei hieß es doch die Nachrichten seien verbindlich?
Danke für den Hinweis @ipadmini22

**Comment by ipadmini22** [comment]
Also du man könnte definitiv danach einen Complaint einlegen und müsste alle Punkte bekommen. Finde es auch uncool, daher warte ich noch eine Antwort bei dem genannten Link. Besonders wenn wir komplexere Probleme bekommen, sind solche Aussagen, die sich plötzlich ändern, total unbrauchbar.

**Comment by nilsreichardt** [comment]
Ich hatte die Tests eingebaut, weil bei W03H03 hat die Übungsleitung damit argumentiert, dass die Methode von außen aufrufbar waren und somit auch ein Bild mit 0px Höhe oder Breite an eine Untermethode hätte übergeben werden können.

Die selbe Argumentation würde hier ebenfalls greifen, weil die Methoden protocted sind somit auch außerhalb der Klasse aufrufbar.

Nach der Aussage von Johannes "Alles im Bereich mergen" (siehe Link im Code) sind die Tests aus meiner Sicht valide.

**Comment by ipadmini22** [comment]
Jup, wie gesagt, die Cases zu erfüllen macht nichts schlimmer. Die initiale Nachricht gab es aber eben auch. Hatte extra deswegen nachgefragt, damit können sie sich eigentlich nicht mehr darauf berufen, dass es trotzdem gehen muss.
Aber tut nicht weh, eben die Checks einzubauen.

**Comment by ipadmini22** [comment]
@JGStyle schließt du dann den Issue?

**Comment by JGStyle** [comment]
> @JGStyle schließt du dann den Issue?

Gerne, ich dachte bis zur Abgabe war's noch hilfreich, jetzt schließe ich ihn natürlich
