### ISSUE TITLE
Problem mit dem picture1 test in w05h02

### ISSUE THREAD

**Issue by Cyro292** [MaximilianAnzinger/pgdp2223-tests#83]
Der Test picture1 geht davon aus, dass der zweidimensionale Array int[4][3] die Höhe 4 und die Länge drei hat. 

Allerdings glaube ich, dass es umgekehrt ist. Der Array hat die Breite 4 und Höhe 3.

**Comment by Cyro292** [comment]
das gleiche gilt übrigens auch für testPicture5

**Comment by DarkbreakerDE** [comment]
"Array int[2][3] hat zum Beispiel Höhe 2 und Breite 3"(Artemis).

**Comment by DarkbreakerDE** [comment]
Dem Entsprechend sollte der Code 
> PinguNetworkTest.java in der Zeile 180 richtig sein:

`public void testPicture5() {
        Picture pic = new Picture("mnb", new int[5][0]);
        assertEquals(pic.getWidth(), 0);
        assertEquals(pic.getHeight(), 5);
        assertTrue(Arrays.deepEquals(new int[5][0], pic.getData()));
    }
`
