### ISSUE TITLE
Können bitte mehr leute permissions kriegen um PRs zu mergen?

### ISSUE THREAD

**Issue by HendrikHuebner** [MaximilianAnzinger/pgdp2223-tests#86]
Es nervt ein bisschen, dass es teilweise mehrere Tage dauert bis pull requests gemerget werden. Vor allem wenn die deadline kurz bevor steht.

**Comment by nilsreichardt** [comment]
Der Grund, warum die restlichen PRs bisher noch nicht gemergt wurden, ist weil diese noch nicht approved wurden uns (Studierenden). In so einem Fall am besten bisschen Druck machen bei uns in der WhatsApp Gruppen mit den Leuten, die Tests schreiben

**Comment by HendrikHuebner** [comment]
Achso ich dachte das kann nur der owner von dem repo machen...

**Comment by nilsreichardt** [comment]
Hier noch die Nachricht, wo wir Max gefragt hatten, ob er immer warten kann, bis jemand die PR approvt hat.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/24459435/203828744-209047ec-f07d-4e63-81b0-8ea08cf59555.png">

https://zulip.in.tum.de/#narrow/stream/1241-PGdP-Organisation/topic/Code.20Review.20bei.20den.20Tests/near/791986

> Achso ich dachte das kann nur der owner von dem repo machen... (bzw. leute mit permissions oder so)

Theoretisch ja, aber auch Dritte können PRs approven, jedoch würde GitHub das z.B. nicht Review zählen, falls es eingestellt hat, dass immer mindestens 1 Person approven muss, muss es überhaupt mögich ist, den Merge Button zu drücken. Da wir sowieso nicht so welche Features nutzen, ist das dann egal 👍

**Comment by MaximilianAnzinger** [comment]
Hauptgrund warum wirklich nur Leute aus der ÜL PRs annehmen sollten/dürfen: Ein quick&dirty "Review" ob die Tests die Implementierung verraten.
Eigentliches Ziel ist es, dass jeder Aufgabensteller sich um die PRs der eigenen Aufgabe kümmert. Da aber schon das kaum bis garnicht funktioniert, will ich da nicht noch ein formales Review dieser Person als Rule vor dem Merge setzen. Ansonsten werden die PRs garnicht mehr angenommen. 😞

**Comment by Anatoly03** [comment]
> Hauptgrund warum wirklich nur Leute aus der ÜL PRs annehmen sollten/dürfen: Ein quick&dirty "Review" ob die Tests die Implementierung verraten. Eigentliches Ziel ist es, dass jeder Aufgabensteller sich um die PRs der eigenen Aufgabe kümmert. Da aber schon das kaum bis garnicht funktioniert, will ich da nicht noch ein formales Review dieser Person als Rule vor dem Merge setzen. Ansonsten werden die PRs garnicht mehr angenommen. 😞

Kann man es irgendwie automatisieren? Sobald du den PR schnell durchgegangen bist, ein "Legal Status Approved" label hinfuegen, der dann den PR direkt akzeptiert sobald ein dritter Kommilitone auch zusagt? Student + UL Labels die zusammen automatisch mergen?

**Comment by cod-eric** [comment]
> Der Grund, warum die restlichen PRs bisher noch nicht gemergt wurden, ist weil diese noch nicht approved wurden von uns (Studierenden). In so einem Fall am besten bisschen Druck machen bei uns in der WhatsApp Gruppen mit den Leuten, die Tests schreiben

Wo Whatsapp-Gruppe?

**Comment by nilsreichardt** [comment]
We can close this issue because I (from the students) received permission to merge to pull requests 👍
