### ISSUE TITLE
Widersprüchliche Test in W05H03

### ISSUE THREAD

**Issue by Friedjof** [MaximilianAnzinger/pgdp2223-tests#92]
### [MessengerTests](https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/52b2f053d68845b66d0d7dd2d0b28694cd966cee/w05h03/test/pgdp/MessengerTests.java#L122)
```java
@Test
@DisplayName("[OPTIONAL] UserArray.addUser")
public void testUserArrayAddUser1() {
    UserArray ua = new UserArray(3);
    User alice = new User(5, "Alice", null);
    ua.addUser(alice);
    ua.addUser(alice);
    Assertions.assertArrayEquals(new User[] {alice, alice, null}, getUsers(ua), "Wrong Users");
}
```
### [UserArrayBehaviourTest](https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/52b2f053d68845b66d0d7dd2d0b28694cd966cee/w05h03/test/pgdp/messenger/test/UserArrayBehaviourTest.java#L74)
```java
@Test
@DisplayName("[OPTIONAL] Add two same users to the array")
void addSameUsers() {
    UserArray userArray = new UserArray(4);
    userArray.addUser(Mike);
    userArray.addUser(Emily);
    userArray.addUser(Mike);
    userArray.addUser(Susan);

    Assertions.assertEquals(3, userArray.size(), "Wrong number of the users in the UserArray. Expected 2, but got " + userArray.size() + " instead");
    Assertions.assertArrayEquals(new User[]{Mike, Emily, Susan, null}, userArray.getUsers(), "Wrong list of users in the UserArray");
}
```
## Beschreibung
Entweder es können Personen doppelt eingefügt werden, oder eben nicht. Wobei es eher mehr Sinn ergibt, wenn ein Benutzer nur einmal eingefügt werden kann. Daher würde ich den Test aus [UserArrayBehaviourTest](https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/52b2f053d68845b66d0d7dd2d0b28694cd966cee/w05h03/test/pgdp/messenger/test/UserArrayBehaviourTest.java#L74) bevorzugen. Allerdings ist dieser Testcase (wie ich es sehe) nicht in der Aufgabenstellung definiert. Daher wäre vielleicht der Test aus [MessengerTests](https://github.com/MaximilianAnzinger/pgdp2223-tests/blob/52b2f053d68845b66d0d7dd2d0b28694cd966cee/w05h03/test/pgdp/MessengerTests.java#L122) eher für die Aufgabenstellung geeignet. Sonst wäre es aber auch vielleicht möglich beide Tests zu entfernen.

**Comment by julian-hartl** [comment]
@Friedjof Beide Tests sind als optional markiert. Wir hatten uns eigentlich intern geeinigt solche Tests in Zukunft rauszulassen, ist aber scheinbar nicht bei allen angekommen. Würde deswegen auch vorschlagen die Tests zu entfernen.
Kannst gerne eine Pull Request aufmachen und die beiden Tests entfernen.

**Comment by nilsreichardt** [comment]
I created a PR for this: https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/101

**Comment by Friedjof** [comment]
Thx
